settings:
  language: "en"
  debug: false
gui:
  roll:
    default-size: 27
    duration-ticks: 60
    tick-interval: 2
sounds:
  roll: "ui.button.click"
  reward: "entity.player.levelup"
hologram:
  max-lines: 6
  default-lines:
    - "&e%crate_name%"
    - "&7store: &fyour.store.com"

