package dev.justteam.justCrates.editor;

public enum EditorInputType {
    CREATE_CRATE,
    CREATE_KEY,
    ADD_COMMAND_REWARD,
    EDIT_COMMAND_REWARD_MENU,
    SET_COMMAND_REWARD_NAME,
    SET_COMMAND_REWARD_WEIGHT,
    SET_COMMAND_REWARD_MATERIAL,
    SET_COMMAND_REWARD_LORE,
    SET_COMMAND_REWARD_COMMAND,
    SET_REWARD_WEIGHT,
    SET_CRATE_PARTICLE,
    SET_CRATE_HOLOGRAM,
    DELETE_CRATE_CONFIRM
}
